[alone]
outputs = ["Sharp Corporation 0x1516"]

[home]
outputs = [ "DP-3", "Sharp Corporation 0x1516" ]

[office]
outputs = [ "Dell Inc. DELL P2421", "Dell Inc. DELL U2713HM" ]

[tv]
outputs = [ "Sharp Corporation 0x1516", "HDMI-A-2" ]

