[alone]
outputs = [
    { name = "Sharp Corporation 0x1516", scale = 1.0}
]

[home]
outputs = [
    { name = "DP-3", scale = 1.0 },
    { name = "Sharp Corporation 0x1516", scale = 1.0 }
]

[office]
outputs = [
    { name = "Dell Inc. DELL P2421", scale = 1.0 },
    { name = "Dell Inc. DELL U2713HM", scale = 1.0 }
]

# [tv]
# outputs = [ "Sharp Corporation 0x1516", "HDMI-A-2" ]

