[alone]
outputs = [
    { name = "LG Display 0x058B", scale = 1.5 }
]

[home]
outputs = [
    { name = "Dell Inc. DELL P2723DE", scale = 1.0 },
    { name = "LG Display 0x058B", scale = 1.5 },
]

[office]
outputs = [
    { name = "Dell Inc. DELL P2421", scale = 1.0 },
    { name = "Dell Inc. DELL U2713HM", scale = 1.0 }
]

[tv]
outputs = [
    { name = "LG Display 0x058B", scale = 1.5},
    { name = "Dell Inc. DELL U2713HM", scale = 1.0 }
]
